apiVersion: v1
kind: Service
metadata:
  name: financial-analysis-streamlit
  namespace: financial-analysis
  labels:
    app: financial-analysis-streamlit
spec:
  type: LoadBalancer
  selector:
    app: financial-analysis-streamlit
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      protocol: TCP
